### ISSUE TITLE
I installed application on JBoss 7.

### ISSUE THREAD

**Issue by infodroid** [peterl1084/cdiexample#1]
How to configure username/password. Or is there any default username/password for system.

**Comment by mstahv** [comment]
Hi, since recent refactoring the app was somewhat wildfly specific. Now, since https://github.com/peterl1084/cdiexample/commit/3bd9df46d838296ce051e3667d306809482fab5f ,  it starts at least on GlassFish again.

JPA backed authentication now works in parallel with the file based ("shiro.ini") version. So you should now be able to log in with "admin/password", even if your Customer table is empty.
